# Generated by Django 4.1.2 on 2024-06-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=12)),
                ('rut', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=30)),
            ],
        ),
    ]
